version: "3.9"
services:
  web:
    container_name: web
    build: ./backend
    ports:
      - "8083:8083"

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - './:/app'
      - '/app/node_modules'
    stdin_open: true
    command: npm start
